# Generated by Django 3.2.9 on 2022-03-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='img')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topic',
                                            to='boards.topic')),
            ],
        ),
    ]
