# Generated by Django 3.2.9 on 2022-03-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名', max_length=64, verbose_name='标签名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话题标签',
                'verbose_name_plural': '话题标签',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.topic')),
            ],
            options={
                'verbose_name': '热门话题',
                'verbose_name_plural': '热门话题',
                'ordering': ['-update_time', '-id'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.tag'),
        ),
    ]
