# Generated by Django 3.2.9 on 2022-03-25 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0004_auto_20220325_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotNews',
            new_name='HotTopics',
        ),
    ]
