# Generated by Django 3.2.9 on 2022-03-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0005_rename_hotnews_hottopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner',
                                    to='boards.topic'),
        ),
    ]
