# Generated by Django 3.2.9 on 2022-03-26 18:22

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('boards', '0006_alter_banner_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tag',
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
