# Generated by Django 3.2.9 on 2022-03-26 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0007_auto_20220327_0222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
