# Generated by Django 3.2.9 on 2022-03-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0008_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='文件url', verbose_name='文件url')),
                ('file_name', models.CharField(help_text='文件名', max_length=48, verbose_name='文件名')),
                ('title', models.CharField(help_text='文件标题', max_length=150, verbose_name='文件标题')),
                ('desc', models.TextField(help_text='文件描述', verbose_name='文件描述')),
                ('image_url', models.URLField(help_text='封面图片url', verbose_name='封面图片url')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文件表',
                'verbose_name_plural': '文件表',
            },
        ),
    ]
