# Generated by Django 3.2.9 on 2022-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0009_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='file_url',
            field=models.CharField(help_text='文件url', max_length=250, verbose_name='文件url'),
        ),
        migrations.AlterField(
            model_name='docfile',
            name='image_url',
            field=models.CharField(help_text='封面图片url', max_length=250, verbose_name='封面图片url'),
        ),
    ]
