# Generated by Django 3.2.9 on 2022-03-27 14:19

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0010_auto_20220327_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 14, 19, 26, 760319, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='docfile',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
