# Generated by Django 3.2.9 on 2022-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0012_alter_docfile_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterModelOptions(
            name='docfile',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '话题', 'verbose_name_plural': '话题'},
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(help_text='板块描述', max_length=100, verbose_name='板块描述'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='板块名', max_length=30, unique=True, verbose_name='板块名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(help_text='回复消息', max_length=4000, verbose_name='回复消息'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(help_text='话题主题', max_length=255, verbose_name='话题主题'),
        ),
    ]
